version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: hrapp_postgres
    environment:
      POSTGRES_DB: hrapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: hrapp_adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
